tokens = [
    # Palabras reservadas y palabras clave (con bordes de palabra \b para que sean reconocidas como palabras completas)
    ('HUNTERSDREAM', r'\bHuntersDream\b'),
    ('NIGHTMARE', r'\bNightmare\b'),
    ('DREAM', r'\bDream\b'),
    ('HUNTER', r'\bHunter\b'),
    ('GREATONES', r'\bGreatOnes\b'),
    ('DJURA', r'\bDjura\b'),
    ('EILEEN', r'\bEileen\b'),
    ('TRUE', r'\btrue\b'),
    ('FALSE', r'\bfalse\b'),
    ('BLOODBOND', r'\bBloodbond\b'),
    ('OLDBLOOD', r'\bOldBlood\b'),
    ('VILEBLOOD', r'\bVileblood\b'),
    ('BLOOD', r'\bBlood\b'),
    ('MARIA', r'\bMaria\b'),
    ('GEHRMAN', r'\bGehrman\b'),
    ('ROM', r'\bRom\b'),
    ('DRUNKENNESS', r'\bDrunkenness\b'),
    ('REST', r'\bRest\b'),
    ('INSIGHT', r'\bInsight\b'),
    ('MADNESS', r'\bMadness\b'),
    ('EYES', r'\bEyes\b'),
    ('PRAY', r'\bPray\b'),
    ('ECHOES', r'\bEchoes\b'),
    ('LIGHT', r'\bLight\b'),
    ('DARKNESS', r'\bDarkness\b'),

    # Operadores y símbolos
    ('GREATER', r'>'),
    ('LESS', r'<'),
    ('GREATEREQUAL', r'>='),
    ('LESSEQUAL', r'<='),
    ('EQUAL', r'=='),
    ('ASSIGN', r'=>'),
    ('NOT', r'!='),
    ('COLON', r':'),
    ('LPAREN', r'\('),
    ('RPAREN', r'\)'),
    ('LBRACE', r'\{'),
    ('RBRACE', r'\}'),
    ('COMMA', r','),
    ('LBRACKET', r'\['),
    ('RBRACKET', r'\]'),
    ('SEMICOLON', r';'),
    ('PLUS', r'\+'),
    ('MINUS', r'-'),
    ('MULTIPLY', r'\*'),
    ('DIVIDE', r'/'),

    # Comentarios y espacios en blanco
    ('COMMENT', r'//.*'),
    ('WHITESPACE', r'\s+'),

    # Literales y tipos de datos
    ('NUMBER', r'\d+(\.\d+)?'),
    ('STRING', r'"[^"]*"'),

    # Identificadores (procesado al final para asegurar palabras clave primero)
    ('IDENTIFIER', r'\b[a-zA-Z_][\w]*\b'),
]
