import re

tokens = [
    ('AWAKEN', r'Awaken'),
    ('CHALICE', r'Chalice'),
    ('HUNTER', r'Hunter'),
    ('BLOODECHO', r'BloodEcho'),
    ('NIGHTMARE', r'Nightmare'),
    ('HUNTERSMARK', r"HuntersMark"),
    ('ETERNALREST', r'EternalRest'),
    ('WHISPER', r'Whisper'),
    ('BLOODMOON', r'BloodMoon'),
    ('HUNT', r'Hunt'),
    ('RITUAL', r'Ritual'),
    ('SANCTUARY', r'Sanctuary'),
    ('VEIL', r'Veil'),
    ('INSIGHT', r'Insight'),
    ('MADNESS', r'Madness'),
    ('SACRIFICE', r'Sacrifice'),

    ('GREATER', r'>'),
    ('LESS', r'<'),
    ('GREATEREQUAL', r'>='),
    ('LESSEQUAL', r'<='),
    ('EQUAL', r'=='),
    ('ASSIGN', r'=>'),
    ('NOT', r'!='),
    ('COLON', r':'),
    ('LPAREN', r'\('),
    ('RPAREN', r'\)'),
    ('LBRACE', r'\{'),
    ('RBRACE', r'\}'),
    ('COMMA', r','),
    ('SEMICOLON', r';'),
    ('PLUS', r'\+'),
    ('MINUS', r'-'),
    ('MULTIPLY', r'\*'),
    ('DIVIDE', r'/'),

    ('LIGHT', r'Light'),
    ('DARKNESS', r'Darkness'),
    ('COMMENT', r'//.*'),
    ('WHITESPACE', r'\s+'),

    ('NUMBER', r'\d+(\.\d+)?'),
    ('STRING', r'"[^"]*"'),
    ('IDENTIFIER', r'[a-zA-Z_]\w*'),
]
